import type { VNode } from 'vue'

/**
 * Base card data interface that all card types must extend.
 * This provides the minimal structure required for the card stack to function.
 *
 * @interface BaseCardData
 * @example
 * ```typescript
 * interface MyCard extends BaseCardData {
 *   title: string
 *   description: string
 *   imageUrl: string
 * }
 * ```
 */
export interface BaseCardData {
  /**
   * Optional unique identifier for the card.
   * If not provided, will be auto-generated by the component.
   */
  _id?: number
  /**
   * Optional original index of the card.
   * Used internally for tracking card positions.
   */
  _index?: number
}

/**
 * Configuration options for the card stack component.
 * All properties have sensible defaults for immediate use.
 *
 * @interface CardStackConfig
 */
export interface CardStackConfig {
  /**
   * Width of individual cards in pixels.
   * @minimum 50
   * @maximum 2000
   * @default 300
   */
  cardWidth: number
  /**
   * Height of individual cards in pixels.
   * @minimum 50
   * @maximum 2000
   * @default 400
   */
  cardHeight: number
  /**
   * Width of the stack container.
   * - number: Width in pixels
   * - string: CSS value (e.g., "100%", "400px")
   * - null: Auto-calculated based on cardWidth + padding
   * @default null
   */
  stackWidth: number | string | null
  /**
   * Sensitivity for drag gestures.
   * Higher values make it easier to trigger card changes.
   * @minimum 0.1
   * @maximum 1.0
   * @default 0.25
   */
  sensitivity: number
  /**
   * Maximum number of visible cards in the stack.
   * Cards beyond this limit will be hidden for performance.
   * @minimum 2
   * @maximum 50
   * @default 10
   */
  maxVisibleCards: number
  /**
   * Scale multiplier for card sizing effect.
   * Controls how much smaller background cards appear.
   * @minimum 0.1
   * @maximum 1.0
   * @default 0.5
   */
  scaleMultiplier: number
  /**
   * Animation speed in seconds for transitions.
   * @minimum 0.1
   * @maximum 2.0
   * @default 0.2
   */
  speed: number
  /**
   * Horizontal padding around the stack in pixels.
   * @minimum 0
   * @maximum 200
   * @default 20
   */
  paddingHorizontal: number
  /**
   * Vertical padding around the stack in pixels.
   * @minimum 0
   * @maximum 200
   * @default 20
   */
  paddingVertical: number
}

/**
 * Internal card data with positioning and display properties.
 * This interface represents a card with all computed layout properties.
 *
 * @interface InternalCard
 */
export interface InternalCard {
  /** Unique identifier for the card (auto-generated if not provided) */
  _id: number
  /** Original index in the cards array */
  _index: number
  /** X position in pixels relative to container */
  xPos: number
  /** Y position in pixels relative to container */
  yPos: number
  /** Scale factor (0-1) for card sizing */
  scale: number
  /** Opacity (0-1) for card visibility */
  opacity: number
  /** CSS display value ("block", "none", etc.) */
  display: string
  /** Z-index for layering (higher values appear on top) */
  zIndex: number
  /** Computed width in pixels */
  width: number
  /** Computed height in pixels */
  height: number
  /** Whether the card is currently being dragged */
  isDragging: boolean
}

/**
 * Touch/Mouse event type union for cross-platform compatibility.
 * Supports both desktop mouse events and mobile touch events.
 */
export type DragEvent = MouseEvent | TouchEvent

/**
 * Card stack component props with generic type support.
 *
 * @template T - The card data type that extends BaseCardData
 * @interface CardStackProps
 */
export interface CardStackProps<T extends BaseCardData = BaseCardData> {
  /** Array of card data objects */
  cards: T[]
  /** Width of individual cards in pixels @default 300 */
  cardWidth?: number
  /** Height of individual cards in pixels @default 400 */
  cardHeight?: number
  /** Width of the stack container @default null */
  stackWidth?: number | string | null
  /** Sensitivity for drag gestures @default 0.25 */
  sensitivity?: number
  /** Maximum number of visible cards @default 10 */
  maxVisibleCards?: number
  /** Scale multiplier for sizing effect @default 0.5 */
  scaleMultiplier?: number
  /** Animation speed in seconds @default 0.2 */
  speed?: number
  /** Horizontal padding in pixels @default 20 */
  paddingHorizontal?: number
  /** Vertical padding in pixels @default 20 */
  paddingVertical?: number
}

/**
 * Component emits interface for type-safe event handling.
 *
 * @interface CardStackEmits
 */
export interface CardStackEmits {
  /**
   * Emitted when cards are being moved/dragged.
   * The value represents the drag progress as a ratio.
   * @param value - Drag progress ratio (-1 to 1)
   */
  move: [value: number]
}

/**
 * Navigation slot props for custom navigation controls.
 *
 * @interface NavSlotProps
 */
export interface NavSlotProps {
  /** Current active card index (0-based) */
  activeCardIndex: number
  /** Function to move to the next card */
  onNext: () => void
  /** Function to move to the previous card */
  onPrevious: () => void
}

/**
 * Card slot props with generic type support.
 * Provides access to both internal positioning data and custom card properties.
 *
 * @template T - The card data type that extends BaseCardData
 * @interface CardSlotProps
 */
export interface CardSlotProps<T extends BaseCardData = BaseCardData> {
  /**
   * Enhanced card object with internal properties and separated custom data.
   * The `data` property contains only your custom card properties.
   */
  card: InternalCard & {
    /** Current index in the stack (may differ from _index due to reordering) */
    $index: number
    /** Your custom card properties (excluding BaseCardData properties) */
    data: Omit<T, keyof BaseCardData>
  }
}

/**
 * Generic slot definitions for the component with full type safety.
 *
 * @template T - The card data type that extends BaseCardData
 * @interface CardStackSlots
 */
export interface CardStackSlots<T extends BaseCardData = BaseCardData> {
  /**
   * Card slot for rendering individual cards.
   * Receives card data with positioning information and custom properties.
   */
  card: (props: CardSlotProps<T>) => VNode | null
  /**
   * Navigation slot for custom navigation controls.
   * Receives current state and navigation functions.
   */
  nav: (props: NavSlotProps) => VNode | null
}

/**
 * Drag data returned from drag handling operations.
 *
 * @interface DragData
 */
export interface DragData {
  /** Current X position of the drag */
  dragXPos: number
  /** Offset from the drag start position */
  activeCardOffset: number
}

/**
 * Constants for component configuration and validation.
 */
export const CARD_STACK_CONSTANTS = {
  /** Minimum card width in pixels */
  MIN_CARD_WIDTH: 50,
  /** Maximum card width in pixels */
  MAX_CARD_WIDTH: 2000,
  /** Minimum card height in pixels */
  MIN_CARD_HEIGHT: 50,
  /** Maximum card height in pixels */
  MAX_CARD_HEIGHT: 2000,
  /** Minimum sensitivity value */
  MIN_SENSITIVITY: 0.1,
  /** Maximum sensitivity value */
  MAX_SENSITIVITY: 1.0,
  /** Minimum number of visible cards */
  MIN_VISIBLE_CARDS: 2,
  /** Maximum number of visible cards */
  MAX_VISIBLE_CARDS: 50,
  /** Minimum scale multiplier */
  MIN_SCALE_MULTIPLIER: 0.1,
  /** Maximum scale multiplier */
  MAX_SCALE_MULTIPLIER: 1.0,
  /** Minimum animation speed in seconds */
  MIN_SPEED: 0.1,
  /** Maximum animation speed in seconds */
  MAX_SPEED: 2.0,
  /** Default debounce delay for resize events */
  RESIZE_DEBOUNCE_DELAY: 250
} as const
